-----------------
-- table: blocks
-----------------
CREATE TABLE IF NOT EXISTS blocks (
  created              TIMESTAMP  NOT NULL DEFAULT now(),
  block_hash           TEXT,
  block_size           BIGINT,
  stripped_size        BIGINT,
  weight               BIGINT,
  block_number         BIGINT     NOT NULL UNIQUE,
  version              BIGINT,
  merkle_root          TEXT,
  block_timestamp      TIMESTAMP  NOT NULL,
  nonce                TEXT,
  bits                 TEXT,
  coinbase_param       TEXT,
  transaction_count    BIGINT,
  input_sum            BIGINT,
  output_sum           BIGINT,
  fee_sum              BIGINT,
  transactional_loss   BIGINT,
  allowed_supply       BIGINT     NOT NULL,
  new_supply           BIGINT,
  current_total_supply BIGINT,
  blocks_till_halving  BIGINT     NOT NULL,
  supply_loss          BOOLEAN    NOT NULL DEFAULT FALSE,
  attributes           JSONB      NOT NULL DEFAULT '{}'::JSONB
);

-----------------------
-- table: transactions
-----------------------
CREATE TABLE IF NOT EXISTS transactions (
  created                TIMESTAMP  NOT NULL DEFAULT now(),
  block_number           BIGINT     NOT NULL REFERENCES blocks(block_number),
  tx_hash                TEXT       NOT NULL UNIQUE,
  tx_size                BIGINT,
  virtual_size           BIGINT,
  version                BIGINT,
  lock_time              BIGINT,
  is_coinbase            BOOLEAN,
  input_value            BIGINT,
  output_value           BIGINT,
  fee                    BIGINT,
  attributes             JSONB      NOT NULL DEFAULT '{}'::JSONB
);

-----------------------
-- table: inputs
-----------------------
CREATE TABLE IF NOT EXISTS inputs (
  created                TIMESTAMP  NOT NULL DEFAULT now(),
  tx_hash                TEXT       NOT NULL REFERENCES transactions(tx_hash),
  input_index            BIGINT,
  spent_transaction_hash TEXT,
  spent_output_index     BIGINT,
  script_asm             TEXT,
  script_hex             TEXT,
  input_sequence         BIGINT,
  required_signatures    BIGINT,
  input_type             TEXT,
  addresses              TEXT[],
  input_value            BIGINT,
  attributes             JSONB      NOT NULL DEFAULT '{}'::JSONB,
  UNIQUE (tx_hash, input_index)
);

-----------------------
-- table: outputs
-----------------------
CREATE TABLE IF NOT EXISTS outputs (
  created                TIMESTAMP  NOT NULL DEFAULT now(),
  tx_hash                TEXT       NOT NULL REFERENCES transactions(tx_hash),
  output_index           BIGINT,
  script_asm             TEXT,
  script_hex             TEXT,
  required_signatures    BIGINT,
  output_type            TEXT,
  addresses              TEXT[],
  output_value	         BIGINT,
  supply_loss            BOOLEAN    NOT NULL DEFAULT FALSE,
  attributes             JSONB      NOT NULL DEFAULT '{}'::JSONB,
  UNIQUE (tx_hash, output_index)
);

-------------------
-- table: anomolies
-------------------
CREATE TABLE IF NOT EXISTS anomolies (
  created              TIMESTAMP  NOT NULL DEFAULT now(),
  block_number         BIGINT     NOT NULL,
  tx_hash              TEXT,
  new_supply           BIGINT     NOT NULL,
  description          TEXT       NOT NULL,
  attributes           JSONB      NOT NULL DEFAULT '{}'::JSONB,
  UNIQUE (block_number, tx_hash)
);

INSERT INTO anomolies
  (block_number, new_supply, description)
VALUES
  (0, 0, 'The 50 BTC supply generated in the first block is not spendable because clients dont include it in the spendable supply.'),
  (91722, 0, 'The 50 BTC supply generated by this block is not spendable because block 91,880 shares an identical transaction ID. This makes the supply in this block not uniquely identifiable and therefore permanently unspendable.'),
  (91812, 0, 'The 50 BTC supply generated by this block is not spendable because block 91,842 shares an identical transaction ID. This makes the supply in this block not uniquely identifiable and therefore permanently unspendable.'),
  (265298, 2499999999, 'This block lost 0.00000001 BTC because it contains a transaction which creates an unspendable output. (txid: 719d8ac8de82622235add948e5acac85216f1db3006861b834dc032d34899821)'),
  (300920, 2499978160, 'This block lost 0.00000001 BTC because it contains transactions which create unspendable outputs. (txids: 49f1a19c2df19db3b21f29a9e35c34ae1740c2bc50604dff569777a6062d6c5a, 1bf308a0ff57449509015ea72fe315f4b806851ecc889d5ab51db79455dfcc6d, d355e9600b098b53439585f3a9fb5a8e1758a61fecd613653e4af49ecb18635a, cf38264dceb6aac5f334ae0009ff1708c9400aa4830f33c4d956b1e86fa09aae)'),
  (300923, 2499989080, 'This block lost 0.00010920 BTC because it contains transactions which create unspendable outputs. (txids: dcab36859f888b9beb6310ef42254109bd9fa577cd0c4d92a81b54968e6aa09f, ed0730318a38ab777b43f178cdf4d3c513638fe357f6f66d2cd4476fb026c65c)');
